services:
  localstack:
    image: localstack/localstack:latest
    hostname: localstack
    ports:
      # Map the port, so you can access the API from the host machine
      - 4566:4566 # LocalStack main endpoint
      - 8000:8000 # DynamoDB local UI
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - PERSISTENCE=1
      - SERVICES=sns,sqs,dynamodb
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./localstack-data:/var/lib/localstack #Persist data
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/init.sh


